name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-v0.1

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install kubeval and kube-linter
      run: |
        curl -sSL https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz | tar xz -C /usr/local/bin
        curl -sSL https://github.com/stackrox/kube-linter/releases/download/v0.2.4/kube-linter-linux.tar.gz | tar xz -C /usr/local/bin
        sudo chmod +x /usr/local/bin/kubeval /usr/local/bin/kube-linter

    - name: Lint Kubernetes manifests with kube-linter
      run: |
        kube-linter lint k8s/

    - name: Validate Kubernetes manifests with kubeval
      run: |
        kubeval k8s/*.yaml

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: jaycynth/flask-app:v0.1

    - name: Scan Docker image with Trivy
      run: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
        aquasec/trivy:v0.1 image --exit-code 1 --severity HIGH,CRITICAL \
        jaycynth/flask-app:v0.1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: jaycynth/flask-app:v0.1

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v0.1'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/network-policy.yaml
