name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  

      - name: Run tests
        run: |
          pytest tests

  build:
    runs-on: ubuntu-latest
    needs: test  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install flake8
          pip install -r requirements.txt

      - name: Lint code
        run: |
          flake8 app.py

      - name: Validate Kubernetes Manifests
        uses: instrumenta/kubeval-action@master
        with:
          files: ./k8s

  docker:
    runs-on: ubuntu-latest
    needs: build  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t jaycynth/flask-app:v0.1 .

      - name: Push Docker image
        run: |
          docker push jaycynth/flask-app:v0.1


  create-cluster:
    runs-on: ubuntu-latest
    needs: docker  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Create Kubernetes Cluster
        run: kind create cluster


  deploy:
    runs-on: ubuntu-latest
    needs: create-cluster  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Set up Kubernetes context
        run: |
          echo "$(kind get kubeconfig-path --name="kind")" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml


      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml --validate=false
          kubectl apply -f k8s/service.yaml --validate=false
